【SEPT-69】メンターは受け取った1on1予約申請を承認・拒否することができる
team-september/mentor-mentee pull request #131
Opened 2021-04-25 02:56 UTC by Ryo-M-49

## チケットへのリンク

https://team-september.atlassian.net/jira/software/projects/SEPT/boards/2?selectedIssue=SEPT-69

## やったこと

メンターは受け取った1on1予約申請を承認・拒否することができる機能

## やらないこと

なし

## できるようになること（ユーザ目線）

メンターは複数の1on1予約依頼を一括で処理可能

同メンティーからのリクエストは１つが承認された際に承認されたもの以外は削除される

## できなくなること（ユーザ目線）

なし

## 動作確認

ブラウザ上で動作確認

## その他

なし

2021-04-25 12:59 UTC, togishima requested changes
債務の分け方もきれいで勉強になります。
自分のコーディングしたところが駄目だったんで恐縮ですが、user_idとなっている箇所だけキャメルケースに直して頂けると幸いです(^_^;)

2021-04-25 12:59 UTC, togishima commented on resources/views/reservation/index.blade.php
> +                                <div>申請日:{{ \Carbon\Carbon::parse($reservation->created_at)->format('Y/m/d') }}</div>
Modelの日付って自動的にCarbonインスタンスにならなかったでしたっけ？
（Modelを極力使わないようにしてるから敢えてですかね？）

2021-04-25 12:59 UTC, togishima commented on app/Repositories/Reservation/IReservationRepository.php
> +    public function store(StoreReservationRequest $request, int $user_id): bool;
スネークケースは敢えてでしょうか？

2021-04-25 12:59 UTC, togishima commented on app/Repositories/Reservation/ReservationEQRepository.php
> +    public function store(StoreReservationRequest $request, int $user_id): bool
これ、多分自分の元のコーディングの方が駄目だったんだと思いますがuser_idをキャメルケースに直して頂けるとです(^_^;)

2021-04-25 12:59 UTC, togishima commented on app/Repositories/Availability/AvailabilityEQRepository.php
>  {
助かります！

2021-04-25 13:05 UTC, togishima commented on resources/views/reservation/index.blade.php
> +                } else { // 未選択の場合、ボーダーつけて値を入れる
細かいところかもしれないですが、動作確認してて思ったのはボーダーの色はもう少し目立つ色の方がいいかなと。。。

2021-04-25 16:55 UTC, Ryo-M-49 reviewed
レビューありがとうございます！修正しましたのでご確認おねがいします🙇

2021-04-25 16:55 UTC, Ryo-M-49 commented on app/Http/Controllers/MenteeReservationController.php
> +}
これ使ってないやつです…消し忘れてたので無視してください

2021-04-25 16:55 UTC, Ryo-M-49 commented on resources/views/reservation/index.blade.php
> +                                <div>申請日:{{ \Carbon\Carbon::parse($reservation->created_at)->format('Y/m/d') }}</div>
クエリビルダでjoinして取ってきてるのでデータ型がモデルインスタンスじゃないんですよね😫

2021-04-26 01:49 UTC, togishima commented on routes/web.php
> +        Route::group(['prefix' => 'profile'], function (): void {
めちゃめちゃ見やすくなりましたね！
整理ありがとうございます！

2021-04-26 03:05 UTC, togishima approved these changes

2021-04-26 03:07 UTC, merged