【SEPT-70】メンターとメンティーは1on1の前日と当日にリマインドされる
team-september/mentor-mentee pull request #151
Opened 2021-05-12 15:06 UTC by Ryo-M-49

## チケットへのリンク

https://team-september.atlassian.net/jira/software/projects/SEPT/boards/2?selectedIssue=SEPT-70

## やったこと

ProfileControllerのリファクタリング
メンターとメンティーは1on1の前日と当日にリマインドされる機能

## やらないこと

なし

## できるようになること（ユーザ目線）

メンターとメンティーは1on1の前日と当日にリマインドされわかりやすくなる。

## できなくなること（ユーザ目線）

なし

## 動作確認

* メンティー側で予約
* メンター側で予約承認
* DBを直接いじり日付を前日に変更
* メンターはプロフィール画面に、メンティーはプロフィール画面と申請知覧画面で前日のバッジ表示を確認できる
* DBを直接いじり日付を当日に変更
* 同様に当日のバッジ表示を確認できる

![image](https://user-images.githubusercontent.com/57619070/117998621-0ae60f80-b37f-11eb-9c4f-b16ab6837375.png)
![image](https://user-images.githubusercontent.com/57619070/117998675-16d1d180-b37f-11eb-846f-164a805df490.png)

## その他

なし

2021-05-14 13:57 UTC, togishima requested changes
おお仕事お疲れ様でした！

何点か気づいたことなどコメントさせて頂きました。
（自分のことは棚に上げてコメントしてるので話半分でｗ）

あと、別件ですが申請日が違う日で出てしまいますね。
多分下記の仕様の関係だと思います。
https://qiita.com/pipiox/items/395bef543e16c93a1fa6

2021-05-14 13:57 UTC, togishima commented on app/Http/Controllers/ProfileController.php
> +        list($userCareer, $careers, $userPurposes, $purposes, $userSkills, $skills, $mentors, $application,
かなり見やすくなっていいと思います。
ここまで大胆にリファクタリングするのであればいっそprofileService->fundprofileDetailから戻す際にprofileDetailsみたいなDTOを作り、そこに各種データを詰めてViewにはそれを渡すようにしたほうがスッキリしそうなイメージです。

また必要に応じてDTOの方で型を定義しておけばそれがドキュメントの代わりにもなると思うのですが、どうでしょうか？（イメージ的にはUpdateでやっているように$profileをそのまま渡す感じ）

2021-05-14 13:57 UTC, togishima commented on app/Repositories/User/UserEQRepository.php
>                  'is_mentor' => 0,
is_mentorカラムってDBの値、確かfalseじゃなかったでしたっけ？
型変換をどこかでやってないのであればfalseにしておいた方が無難かなと思います。

2021-05-14 13:57 UTC, togishima commented on app/Repositories/User/UserEQRepository.php
> +                'nickname'  => $userInfo['nickname'],
こういう細かい気遣い、本当にありがたいです

2021-05-14 13:57 UTC, togishima commented on app/Repositories/User/UserEQRepository.php
>      {
名前の冗長性の排除、Goodだと思います！

2021-05-14 13:57 UTC, togishima commented on app/Services/ProfileService.php
>              $application,
ここはkey,valueの配列かstdObjectで返してしまうのも一つかなと思いました。
（Viewも手直ししないといけないので面倒ですが、、、せっかくここまでやったなら、という気持ちｗ

2021-05-14 13:57 UTC, togishima commented on app/Services/UrlService.php
> +    protected $urlRepository;
そもそもURLってProfileに紐づくサブテーブルという認識だったのですが、Repository別にしたほうがいいんでしょうか？

Repositoryに関しては本来ルートエンティティに対して用意するものだっていう認識だったので、そういう意味ではProfileがルートエンティティなのかな？と思いまして

2021-05-14 13:57 UTC, togishima commented on app/Services/UserService.php
> +    public function getOrCreate($auth0User)
LGTM

2021-05-14 13:57 UTC, togishima commented on resources/views/reservation/mentee/index.blade.php
> +                                    @if(\Carbon\Carbon::parse($reservation->date)->eq(\Carbon\Carbon::today()->addDay(1)))
addDay()の場合引数って要らなかったような？

2021-05-18 16:37 UTC, Ryo-M-49 commented on app/Http/Controllers/ProfileController.php
> +        list($userCareer, $careers, $userPurposes, $purposes, $userSkills, $skills, $mentors, $application,
ViewModelとかの導入はおおがかりになりそうなのでまた別のチケットでやりましょうｗ

2021-05-18 16:39 UTC, Ryo-M-49 commented on app/Services/ProfileService.php
>              $application,
これも長いのでどこかで直したいですね😅

2021-05-18 16:40 UTC, Ryo-M-49 commented on app/Services/UrlService.php
> +    protected $urlRepository;
おっしゃる通り分けなくていいと思います😅
ルートエンティティを経由する実装は別チケットを切って他のクラスも含めまとめてやりましょう。

2021-05-19 00:32 UTC, togishima approved these changes
LGTMです！

2021-05-19 11:35 UTC, merged