Sept 36
team-september/mentor-mentee pull request #19
Opened 2021-01-22 06:49 UTC by mizuki793

## チケットへのリンク
https://team-september.atlassian.net/jira/software/projects/SEPT/boards/2?selectedIssue=SEPT-36
* https://example.com

## やったこと
* このプルリクで何をしたのか？
スキル欄を編集して登録をすると、編集後のプロフィールが表示されている
プロフィールのスキル欄を編集できる

## やらないこと
なし
* このプルリクでやらないことは何か？（あれば。無いなら「無し」でOK）

## できるようになること（ユーザ目線）
profile画面での更新
* 何ができるようになるのか？（あれば。無いなら「無し」でOK）

## できなくなること（ユーザ目線）
なし
* 何ができなくなるのか？（あれば。無いなら「無し」でOK）

## 動作確認
localのみ動作確認
* どのような動作確認を行ったのか？　結果はどうか？

## その他

* レビュワーへの参考情報（実装上の懸念点や注意点などあれば記載）
sept-33の内容が混じってしまったのですが、sept-36の最後のコミット
「スキル欄を編集して登録をすると、編集後のプロフィールが表示されている」を見てもらえると助かります。
(contorollerの値の渡し方の理解が不十分なため、\app\Http\Controllers\ProfileController.phpが分かりにくいはずです、そこを中心に見てもらえると嬉しいです)

2021-01-23 08:33 UTC, Ryo-M-49 commented
まずなにより、最近PHPとLaravel勉強し始めたばかりとは思えないぐらいよく理解して書けていて本当にすごいです！
本業と別で作業しているのに作業ペースが速いのにもびっくりしてます。
以下に書くことは知らなくて当然なので、今後のコーディングにいかしてみてください！

routeにはすべて名前を付けておきましょう
https://qiita.com/kazuhei/items/935257b0d72fa314d461

エディタに自動フォーマットを導入してください
https://qiita.com/mitashun/items/e2f118a9ca7b96b97840
→これに関してはCIで防いでるはずなんですが機能していないので後で見てみます！

名前空間が宣言されているクラスを使う際に先頭のバックスラッシュは不要です
https://qiita.com/7968/items/1e5c61128fa495358c1f

主キーと外部キーの型は同じである必要があるので
usersテーブルのマイグレーションファイルで主キーを符号なしINT型にしたいのであれば
対応する外部キーの型もすべて合わせる必要があります。
$table->id()は$table->bigIncrements('id')のエイリアスなのでBIG INT型になります。
必要に応じてどちらかに統一してください。いったんBIG INT型に戻しておきます。

これは好みの問題かもしれませんが中途半端な省略形にするぐらいであれば
多少長くなってもいいので完全な単語で書いてもらったほうがわかりやすいかもしれません。
例）$prof -> $profile, 

オブザーバを使うことでユーザーレコードが作られると付随するプロフィール、URL、プロフィールURLも作られるようにできます。
ただし処理の流れがわかりにくくなる、Laravelの機能に依存することになるなどのデメリットもあります。
https://www.ritolab.com/entry/35

全てのカラムがfillableで問題ない場合は、
カラムの記述漏れなどもあるので$guarded = [];
という書き方でも良いです。

findとfindOrFailを使い分けると良いです。
findで見つからなかったらこういう処理をしたいというときはfindでよくて、
見つからないという想定はしておらず、万が一見つからない場合にエラーを投げたい、
という状況の時はfindOrFailにします。
https://nebikatsu.com/8589.html/

今回はLaravelにどっぷり浸かるという想定で作っちゃうので、
リレーションの機能もガンガン使っちゃってください。
findで書いているところで、リレーションのメソッド使えば簡単に書けるようなところは書き換えちゃいましょう。

コントローラーは基本的にロジックは書かず、各クラスに処理を委譲するように書いていきましょう。
あくまで処理を呼び出す立場に徹底することで、ファットコントローラーを防げます。
例えばモデルオブジェクトを取得する処理は該当テーブルに対応するモデルクラスに書く、
Urlを取得する処理（urlSearch()）はUrlServiceクラスに切り出す、などです

スキルの種別によってバッジを色分けするためにスキルタイプカラム追加してくれたのナイスです！

ユーザーが動的に値を入力する処理にはバリデーションが必須です。
FormRequestを使ってバリデーションを追加しましょう。
twitterのURLとかも正規表現で厳密にチェックしてもいいんですが、ユーザーからすると不便なのでいったんstringのみにしてます。
https://readouble.com/laravel/8.x/ja/validation.html

プロフィールのアップデート時に関連して、
複数のテーブルを一度に更新するような処理の場合、トランザクションを利用してください。
途中で処理が異常終了した場合に各テーブル間で矛盾が生じる可能性があります。
https://readouble.com/laravel/8.x/ja/database.html

その他細かい修正点はコード見てみてください。

2021-01-23 08:37 UTC, Ryo-M-49 commented
あ、あとスキルと希望欄も編集できるようにしておいてもらえると助かります！

2021-01-23 09:00 UTC, Ryo-M-49 requested changes
スキルと希望も編集できるようにしてもらえると助かります！（見積もり甘すぎましたねこのタスク、倍ぐらいとってもよかった）

2021-01-23 09:38 UTC, mizuki793 commented
全部ソースを見れてないのですが、取り急ぎお礼だけ。
Ryoさん、ありがとうございます。

>スキルと希望も編集できるようにしてもらえると助かります！

->これは、スキルと希望を追加できる別のedit画面を追加する形で問題ないでしょうか?(若干気になったので……)

2021-01-23 10:37 UTC, Ryo-M-49 commented
スキルと希望ってこっちで固定データをバーッと入れてユーザーはその中から選択する想定でしたっけ？
別画面作るよりはeditビューの中で完結する方が自然かなあという気はします。工数的にも大変なので。
ドロップダウンで候補を選択するたび欄に追加されて更新ボタンで確定する、とかですかね？
とりあえず方針だけ共有してもらえればお任せします👌

2021-01-23 11:06 UTC, mizuki793 commented
>スキルと希望ってこっちで固定データをバーッと入れてユーザーはその中から選択する想定でしたっけ？

なるほど。
editのviewに追加する旨、わかりました。

希望はメンターが提供するものになるので追加できる人間はメンターに限った方がいいかもしれませんね。
スキルは限るべきかはわかりませんが……。

(何を固定入れるか失念してしまったので、固定で入れる項目があるかどっかで精査したほうがいいかもしれませんね。)

2021-01-23 11:15 UTC, Ryo-M-49 commented
スキルは自由入力だとバッジの色分けが大変になりますね、あと同じスキルでも表記にバラツキが出ます。シーダーでバーッとメジャーどころの言語や技術のレコード入れてそっから選んでもらうっていうのでいいかもです。
希望の方は現状3種類ぐらいじゃありませんでした？1on1, チーム開発希望、両方希望(正確な内容忘れました)とかだったきが

2021-01-23 11:24 UTC, mizuki793 commented
>希望の方は現状3種類ぐらいじゃありませんでした？1on1, チーム開発希望、両方希望(正確な内容忘れました)とかだったきが

スキルに関して了解です。

希望は確かに、現状1on1, チーム開発希望(+両方選択)だけなので、希望も暫くはシーダーでもいいのかもしれません。

2021-01-24 04:37 UTC, mizuki793 commented
そういえば、margeの権限は私は持っていないので、あつまるさんかryoさんお願いします。

2021-01-24 06:07 UTC, akkkn0426 approved these changes, later dismissed

2021-01-29 04:54 UTC, mizuki793 commented
修正しました。
コメントでの承認をしてもらえると嬉しいです

2021-01-29 09:42 UTC, Ryo-M-49 commented
お疲れ様です！

下記確認いただけますか？
* 画面幅狭くなるとチェックボックスがはみ出す
* スキル欄にチェックボックスが表示されない
![image](https://user-images.githubusercontent.com/57619070/106258528-4857de80-6261-11eb-9a5a-f5cf19affdf5.png)
* 希望欄に両方チェックもしくはチーム開発希望にチェックを入れて更新後、再度編集画面に入ると1on1希望にだけチェックが入った状態になっている

2021-01-29 09:51 UTC, mizuki793 commented
すみません。　
明日以降直します。

2021-01-30 03:22 UTC, Ryo-M-49 commented
追加で、ちょっと細かくて申し訳ないんですがチェックボックスはボックスをクリックしないとチェックつかない状態になってると思うんですが、ラベル（1on1希望、チーム開発希望の文字列の部分）をクリックでもチェック付けられるようにしてもらえると助かります！
label属性とid属性に同じ値を指定することでできます。

2021-01-30 13:29 UTC, mizuki793 commented
チェックボックスのlabel対応 と スマホサイズでのチェックボックス見切れ対応(チェックボックス未表示を含むをしました。

動確は自分の見える範囲でしかしてないので、もしかしたらまた何か出るかもしれませんが、
よろしくお願いします。

2021-01-30 13:32 UTC, mizuki793 commented
vscodeでソースを触っているのですが、以前教わったソースフォーマットだとこれくらいの差分が出てしまいます。

これは問題ないでしょうか?
(同じファイルで触った覚えのないところまで差分が出て見にくい気がする。)

https://github.com/team-september/september/pull/19/commits/19fa403074fc627268c458a048179eb4f3a2fc2d

2021-01-30 13:47 UTC, Ryo-M-49 commented
いい感じです、助かります！あとスキルのチェックボックスも同じようにラベルでチェックできるようにしてもらえますか…？

フォーマットに関しては規約にPSR2を使うとか統一しないとこうやってdiffがめっちゃ出ちゃいますね。
あとで統一してもらうことになりますがいったん大丈夫です。

2021-01-30 14:16 UTC, Ryo-M-49 commented
今php_cs.distファイルを見たらPSR2を適用するようになっていたのでVSCodeでもフォーマット時にPSR2に準拠するように設定してみてください。
https://mrkmyki.com/windows10%E3%81%AEvs-code%E3%81%A7php%E3%81%AE%E3%82%B3%E3%83%BC%E3%83%89%E3%83%95%E3%82%A9%E3%83%BC%E3%83%9E%E3%83%83%E3%83%88%EF%BC%88psr-2%EF%BC%89%E3%82%92%E8%87%AA%E5%8B%95%E3%81%A7%E8%A1%8C

あとはcomposer fixでpush前に一度フォーマットもかけておくと良いです。
CI時のフォーマットチェックが機能してないようなので直します

2021-01-30 15:40 UTC, Ryo-M-49 approved these changes
お疲れさまでした！

2021-01-30 15:40 UTC, merged