Sept45
team-september/mentor-mentee pull request #37
Opened 2021-02-05 03:10 UTC by mizuki793

## チケットへのリンク
* https://example.com
https://team-september.atlassian.net/jira/software/projects/SEPT/boards/2?selectedIssue=SEPT-45

## やったこと
* このプルリクで何をしたのか？
メンター側の一覧表示画面の作成

## やらないこと

* このプルリクでやらないことは何か？（あれば。無いなら「無し」でOK）
なし
## できるようになること（ユーザ目線）

* 何ができるようになるのか？（あれば。無いなら「無し」でOK）
応募一覧が表示できる
## できなくなること（ユーザ目線）

* 何ができなくなるのか？（あれば。無いなら「無し」でOK）
なし
## 動作確認
ローカルのみ
* どのような動作確認を行ったのか？　結果はどうか？

## その他

* レビュワーへの参考情報（実装上の懸念点や注意点などあれば記載）
![image](https://user-images.githubusercontent.com/51521774/106984208-7a5dc900-67aa-11eb-9d64-c4b2a095faf7.png)

2021/2/5
とりあえず、↑のような画面を作りました。
作りこみは甘いと思うのでマージはせず、進捗報告という形で見てもらえると嬉しいです

2021-02-06 02:56 UTC, Ryo-M-49 requested changes
動確もしましたがUI含めていい感じです！
細かいところは各コメントをみてもらうとして

* PSR-2にも記載されているカンマ後のスペースなどがまだ適用されていないようです。エディタのフォーマッタ設定をもう一度見直してみてください。
* 同じファイルを何回も修正した場合、「修正した、削除した」といったコミットを作るのではなく、rebaseを使うなどして過去のソースを直接いじり、コミットとしては1つになるようにしてみてください。

2021-02-06 02:56 UTC, Ryo-M-49 commented on app/Http/Controllers/ApplicationController.php
> +                $coustomers[] = array('id'=>$coustom->_id,'name'=>$user->name,'created_at'=>$create);
$customersだとお客さん的なイメージでわかりにくいので$applications（応募）に対応する$applicants（応募者）に変えましょうか。
あとまだエディタのフォーマッタがちゃんと適用されてないっぽいですね。例えば配列のキーと=>のあとやカンマのあとにスペースがないので読みにくいです。

2021-02-06 02:56 UTC, Ryo-M-49 commented on resources/views/application/index.blade.php
> +        </div>
UIも見やすくて個人的にはめっちゃいい感じです！

2021-02-06 02:56 UTC, Ryo-M-49 commented on app/Http/Controllers/ProfileController.php
> +        $mentor_applied = $application ? $application->mentor : null;
この辺ってindex()でも共通の処理だった気がするので関数にまとめたりできます？

2021-02-06 02:56 UTC, Ryo-M-49 commented on routes/web.php
> +        Route::get('/profile/show/{id}', 'ProfileController@show')->name('profile.show');
routeでパラメータを渡してcontrollerでインスタンス化したいとき、暗黙の結合が便利です。
https://readouble.com/laravel/master/ja/routing#implicit-binding

2021-02-06 02:56 UTC, Ryo-M-49 commented on app/Http/Controllers/ApplicationController.php
> +            foreach ($coustomer as $coustom) {
こういった修正のコミットはレビューするうえで見にくくなるので、git rebaseを使って過去のコミットにさかのぼってに修正してみてください。

2021-02-06 02:56 UTC, Ryo-M-49 commented on app/Http/Controllers/ProfileController.php
>          $user_career = $profile->career;
idをパラメータに渡す場合はPolicyやGateを使って認可制御しましょう。
今回は渡さないのでOK

2021-02-08 05:26 UTC, mizuki793 commented on app/Http/Controllers/ProfileController.php
> +        $mentor_applied = $application ? $application->mentor : null;
no01 共通処理の追加に反映

2021-02-08 08:36 UTC, mizuki793 commented on routes/web.php
> +        Route::get('/profile/show/{id}', 'ProfileController@show')->name('profile.show');
no02暗黙の結合追加に反映

2021-02-08 13:32 UTC, Ryo-M-49 approved these changes

2021-02-08 13:32 UTC, merged