【Sept 48】メンターは一覧から承認ボタンを押すと、そのユーザーをメンティーとして承認することができる
team-september/mentor-mentee pull request #52
Opened 2021-02-18 14:42 UTC by mizuki793

## チケットへのリンク
*https://team-september.atlassian.net/jira/software/projects/SEPT/boards/2?selectedIssue=SEPT-48

## やったこと
メンターが一覧から承認ボタンを押すと、そのユーザーをメンティーとして承認できるようにする

## やらないこと
なし
* このプルリクでやらないことは何か？（あれば。無いなら「無し」でOK）

## できるようになること（ユーザ目線）
メンティーの承認ボタンの押下、承認

## できなくなること（ユーザ目線）

## 動作確認
ローカルでの画面確認
* どのような動作確認を行ったのか？　結果はどうか？

## その他

2021-02-21 15:42 UTC, Ryo-M-49 requested changes
レビュー遅れちゃってすみません！そんなに大した内容ではないですがコメント確認いただいて修正してもらえると助かります！
相変わらず仕事早すぎです、バリデーションとかリポジトリ―とかも、使い方ばっちりですね😀

2021-02-21 15:42 UTC, Ryo-M-49 commented on app/Http/Controllers/ApplicationController.php
> +        $user_id = $user->id;
複合語の変数はキャメルケースでお願いします！

2021-02-21 15:42 UTC, Ryo-M-49 commented on app/Http/Controllers/ApplicationController.php
> +            $coustomers[] = array('id'=>$coustom->$user_category,'name'=>$user->name,'created_at'=>$create);
正しいつづりはcoustmerではなくてcustomerです！あとcustomerはお客さんという意味なので変数名はapplicantsのほうが実際にやっていることと一致しているかなあと個人的には思います。
あと、collection型の$applicationsを配列で取得しなおしてforeachしてますが、map()を使うとcollection型のままループ回して配列を取得できますし、空配列を事前に用意する必要もないのでシンプルに書ける気がします。

2021-02-21 15:42 UTC, Ryo-M-49 commented on app/Http/Controllers/ApplicationController.php
> +        $user_category = $user->is_mentor ?'mentee_id':'mentor_id';
$userCategory

2021-02-21 15:42 UTC, Ryo-M-49 commented on app/Http/Controllers/ApplicationController.php
> +        $mentor_id = $request->mentor_id;
$mentorId

2021-02-21 15:42 UTC, Ryo-M-49 commented on app/Http/Controllers/ApplicationController.php
> +            foreach ($mentees as $mentee_id) {
$menteeId

2021-02-21 15:42 UTC, Ryo-M-49 commented on app/Http/Requests/ApplicationUpdateRequest.php
> +    }
バリデーションばっちりですね！さすがです😀

2021-02-21 15:42 UTC, Ryo-M-49 commented on app/Repositories/Application/ApplicationEQRepository.php
> +    }
リポジトリ―も使いこなせてますね、理解早すぎです😆

2021-02-21 15:42 UTC, Ryo-M-49 commented on routes/web.php
> +        Route::post('/application/update/', 'ApplicationController@update')->name('application.update');
とりあえず末尾は/なしで統一しちゃいましょうか！

2021-02-21 15:42 UTC, Ryo-M-49 commented on resources/views/application/index.blade.php
>  @endsection
複数人応募があるときに応募アイテムの幅を統一してもらえると助かります！
![スクリーンショット 2021-02-22 000028](https://user-images.githubusercontent.com/57619070/108630022-23dcd400-74a6-11eb-9244-7a73e6b4317b.png)

あと、チェックボックスの表示もうちょっときれいな感じにできますかね？
応募者の名前と縦並びじゃなくて名前の横に表示させるとかそれぐらいの変更でもだいぶきれいに見えそうです。

2021-02-23 13:54 UTC, mizuki793 commented on app/Http/Controllers/ApplicationController.php
> +            $coustomers[] = array('id'=>$coustom->$user_category,'name'=>$user->name,'created_at'=>$create);
map にした際に変数($userCategory)を取るのが少し難しかったため、少し保留にしてもらえると嬉しいです。

2021-02-24 11:24 UTC, mizuki793 commented
レビュー部分、反映しました。確認お願いします。

2021-02-24 12:09 UTC, Ryo-M-49 approved these changes
ばっちりですありがとうございます😀

2021-02-24 12:09 UTC, merged