【Sept 49】メンターは承認したくない応募を一覧画面でキャンセルボタンを押して応募をキャンセルできる
team-september/mentor-mentee pull request #60
Opened 2021-02-25 12:33 UTC by mizuki793

## チケットへのリンク

* https://team-september.atlassian.net/jira/software/projects/SEPT/boards/2?selectedIssue=SEPT-49

## やったこと
メンターは承認したくない応募を一覧画面でキャンセルボタンを押して応募をキャンセルする処理

## やらないこと
* なし

## できるようになること（ユーザ目線）
メンターは承認したくない応募を一覧画面でキャンセルボタンを押して応募をキャンセルできる

## できなくなること（ユーザ目線）
なし

## 動作確認
* ローカル環境での確認
* どのような動作確認を行ったのか？　結果はどうか？

## その他

* レビュワーへの参考情報（実装上の懸念点や注意点などあれば記載）

2021-02-27 10:49 UTC, Ryo-M-49 requested changes

2021-02-27 10:49 UTC, Ryo-M-49 commented on app/Http/Controllers/ApplicationController.php
>              return redirect()->route('application.index')->with(['alert' => '応募を拒否しました。']);
個人的な感覚になってきちゃうかもなんですが、赤色のメッセージ表示はユーザーがアクションに失敗したときに表示されるイメージなので、赤色のメッセージが出ると「あれ、拒否に失敗したのかな？」と思っちゃうかもしれません。
successメッセージとして表示のほうがしっくりと思いました！

2021-02-27 10:49 UTC, Ryo-M-49 commented on app/Http/Controllers/ApplicationController.php
>              $this->applicationRepository->updateApprovedApplication($mentorId, $menteeId);
updateRejectedApplication()の間違いですかね？
拒否してもstatusがapprovedになってapproved_atが更新されちゃってます。

2021-02-27 10:49 UTC, Ryo-M-49 commented on resources/views/application/index.blade.php
>                              </lavel>
綴りが間違ってて閉じタグとして認識されてないですね。</label>です。
あとそこから2つ下の</div>や<br/>など余計なタグが入っちゃってる気がするのでもう一度見直してみてください😀

2021-02-27 10:49 UTC, Ryo-M-49 commented on app/Http/Requests/ApplicationUpdateRequest.php
>  }
フロント側でinput属性はいくらでもいじれちゃうので、ユーザー側で値を送信するような処理ではバックエンドのバリデーションは基本的に設定してください。
どうしてもわからなければ最悪とりあえずrequiredだけでもいいかもしれません😂

2021-02-28 14:11 UTC, Ryo-M-49 approved these changes
修正助かります！応募拒否したときにまだapproved_atが更新されちゃっていたのでこちらで直しました。
画面上の処理だけで動作確認を済ませるのではなくて、DB側の処理も含めて期待通りになっているかも確認するよう意識してもらえると助かります😀

2021-02-28 14:11 UTC, merged

2021-02-28 14:17 UTC, mizuki793 commented
修正ありがとうございます。
approved_at見えてなかったです、次から気を付けます。

2021-02-28 14:36 UTC, mizuki793 commented
仕様を掴めてなくてため追記で質問になってしまいますが、
応募許可の場合はapproved_atを更新するという処理で間違いないですか？
現状はその形で更新しているため、少し気になりました。
宜しくお願いします。

2021-02-28 15:14 UTC, Ryo-M-49 commented
その認識で大丈夫です！
誰が同期なのか判定できるようにapproved_atを用意してるって感じです👌