Feature/sept 62
team-september/mentor-mentee pull request #71
Opened 2021-03-04 15:24 UTC by togishima

## チケットへのリンク

SEPT-62
https://team-september.atlassian.net/browse/SEPT-62?atlOrigin=eyJpIjoiYzM5YjVlMGEwMjhiNGEyMzk2YTU0YzVlMzAxZjlhYmIiLCJwIjoiaiJ9

SEPT-64
https://team-september.atlassian.net/browse/SEPT-64?atlOrigin=eyJpIjoiZWI5NTU0MzViNTRmNDRkNjkwMzViMTZlMjk2NjI0M2UiLCJwIjoiaiJ9

## やったこと

メンターが該当日と時間を選んで予約可能日時を指定できるようにした。

## やらないこと

イケてるUIでの実装（工数取れなかったため、一先ずこんな感じで…）

## できるようになること（ユーザ目線）

メンターは予約可能な日時を登録できるようになる

## できなくなること（ユーザ目線）

なし

## 動作確認

ブラウザでの動作確認

## その他

2021-03-05 04:56 UTC, mizuki793 commented
お疲れ様です。
あきのです。

「カレンダーのページ」の作成ありがとうございます。

隠れた要件として(これはどこにも書いていなかったので申し訳ない)、
* メンターは複数の空いている日程を複数選択できる　
というものがあった気がするのですが、実装できるでしょうか?
ボードなどにも書かれていないものなので(これは以降どうにか改善しましょう)心苦しいのですが、考慮のほうよろしくお願いします。

@Ryo-M-49 
もし、隠れた要望が他にあったらボードコメントにつけ加える等してもらえると助かります。
(私もしっかり覚えている部分が少ないので)

取り急ぎ、以上です。
よろしくお願いします。

2021-03-05 07:38 UTC, togishima commented
ぉ、なるほど。
そしたらチェックボックスを用意しておいて、まとめて送信してリクエストの$request->dateが配列になるように変更しましょうか。詳細画面はそれをforeachとかでフォーム複数作成する感じで、どうでしょう？

2021-03-05 07:59 UTC, mizuki793 commented
@togishima 
なるほど、その形で試してみましょう。

2021-03-05 08:48 UTC, mizuki793 commented
@togishima 
よくよく考えたら自分の方でモーダルで出せば十分要望をかなえられる気もしてきたので修正不要です。
紛らわしいことして申し訳ございません。

2021-03-05 08:51 UTC, togishima commented
ぁ、なるほど～
確かに、カレンダーから飛んだ先で動的にフォーム追加ってのでもいけそうですね！

2021-03-14 18:43 UTC, togishima commented
今週は完全に私がボトルネックになってしまってチームの進捗大幅に遅らせてしまいました…申し訳ありません。
一先ずカレンダーの実装はできたのですが、実際に設定・申し込みをできる状態には至っていないです。

明日仕事が定時で終われば駆け込みでもう少し進めますが、一先ず現時点でのSEPT-62, SEPT-64の要件は達成できると思います。
SEPT-6の要件達成には変遷先の画面でメンターは実際に設定を、メンティーは申し込みをできるような機能の実装が必要となります。

2021-03-15 09:04 UTC, Ryo-M-49 commented
気になさらず無理のない範囲で進めてください！

2021-03-16 15:52 UTC, togishima commented
少し追加コミットさせてもらいました。
- Header View用のmiddleware設定とそれに伴う一部記述のリファクタ
- CalendarServiceクラスのリネーム、リファクタ　⇒　この機能の主目的は1 on 1の予約可能日取得がメインのため

2021-03-22 16:32 UTC, Ryo-M-49 requested changes
ごちゃごちゃしそうな処理がわかりやすく書かれていて勉強になりました！
大した内容ではないんですが少しだけコメントしました😀

2021-03-22 16:32 UTC, Ryo-M-49 commented on app/Http/Controllers/ReservationController.php
> +        $Service = new CalendarService();
アクション内でnewせずにコンストラクターインジェクションで外部から注入するほうが依存関係が少なく済むと思います！

2021-03-22 16:32 UTC, Ryo-M-49 commented on app/Services/CalendarService.php
> +    protected UserEQRepository $UserEQRepository;
キャメルケースなので語頭は小文字でお願いします！

2021-03-22 16:32 UTC, Ryo-M-49 commented on app/Services/CalendarService.php
> +        }
$_GET使うのであればエスケープの上で入力値チェックしたほうがいいかもです。
あとたしかRequestオブジェクトからURLのパラメータ安全に取れた気がします。

2021-03-22 16:32 UTC, Ryo-M-49 commented on app/Repositories/Mentorship/MentorshipEQRepository.php
> +        $Mentorship = Mentorship::where('mentee_id', $mentee_id)->first();
ここも小文字でお願いします！

2021-03-24 15:05 UTC, togishima commented
- 先日話していたサービスプロバイダの統合
- 上記に伴いサービスクラスのリポジトリクラスの利用をコンストラクタインジェクションへ変更
- 一部インスタンス変数の記述修正

2021-03-26 18:23 UTC, Ryo-M-49 requested changes
メンターの1on1予約のに日時設定に関しては挙動確認はできたのですが、メンティー側の予約がエラーで確認できてないので修正していただけたらまた確認させてもらいます！

2021-03-26 18:23 UTC, Ryo-M-49 commented on app/Providers/RepositoryServiceProvider.php
> +    }
助かりましたー😭

2021-03-26 18:23 UTC, Ryo-M-49 commented on resources/views/includes/header.blade.php
> +                        </a>
ユーザーに承認済みのメンターが存在しない場合は表示しないようにしてもらいたいです。
routeファイルも同様に修正必要ですかね。
![image](https://user-images.githubusercontent.com/57619070/112673289-e3f37d00-8ea7-11eb-8a51-4f6de9ee49cb.png)

2021-03-26 18:23 UTC, Ryo-M-49 commented on resources/views/reservation/index.blade.php
> +            <a class="btn btn-outline-secondary p-2" href="?ym={{ $nextMonth->format('Y-m') }}">次の月 &gt;&gt;</a>
メンターのユーザーで/reservationにGETアクセスすると以下のエラーになりました。
DateTime型ではなくString型の値にformat()を呼び出してるからっぽいですかね。
確認したところ$prevMonth, $nextMonth, $currentMonthはすべてformat()呼び出す前の時点でフォーマットされてるのでいらないかもしれないですね。意図があるかもしれないので修正はいったんおぎさんにお任せします！
![image](https://user-images.githubusercontent.com/57619070/112674998-f4a4f280-8ea9-11eb-997c-fa49d13a8b10.png)

2021-03-26 18:23 UTC, Ryo-M-49 commented on resources/views/reservation/setting.blade.php
> +                        >
一回更新してからまたこの画面に来た時に、前回チェック付けた時間はチェック済みで表示してくれるほうが使いやすいかもしれないですね。
もし余裕あればお願いしたいですがここは後回しでもいいと思います😂

2021-03-26 18:23 UTC, Ryo-M-49 commented on app/Http/Controllers/ReservationController.php
> +    }
reserveというアクションがないのでメンティーの状態で1on1予約画面に入って予約ボタンを押すとエラーになります。
![image](https://user-images.githubusercontent.com/57619070/112676361-ac86cf80-8eab-11eb-81a3-2ed8927da73a.png)

2021-03-26 18:31 UTC, Ryo-M-49 commented
あ、すみません勘違いしてました！今回はメンティーがメンターの空き状況を確認できる、というところまででしたね。
reserveのエラーの所は気にしないで大丈夫です！

2021-03-27 04:49 UTC, togishima commented on resources/views/reservation/index.blade.php
> +            <a class="btn btn-outline-secondary p-2" href="?ym={{ $nextMonth->format('Y-m') }}">次の月 &gt;&gt;</a>
あれ？おかしいですね。。。コントローラーでフォーマットかけるのやめたはずなんですけど。。。
もっかいコード確認してみます

2021-03-27 04:50 UTC, togishima commented on resources/views/includes/header.blade.php
> +                        </a>
ここは修正かけますね〜

2021-03-27 04:50 UTC, togishima commented on resources/views/reservation/setting.blade.php
> +                        >
これも修正かけたはずなんですけど。。。なんで反映されてないんだろ？

2021-03-27 05:25 UTC, togishima commented on resources/views/reservation/index.blade.php
> +            <a class="btn btn-outline-secondary p-2" href="?ym={{ $nextMonth->format('Y-m') }}">次の月 &gt;&gt;</a>
![image](https://user-images.githubusercontent.com/65173657/112710948-1df46b80-8f08-11eb-8fa0-3354d4d142a3.png)
同じようにアクセスしましたが普通にアクセスできてるんですが…何が悪いんでしょうかね(-ω-;)ウーン

2021-03-27 05:40 UTC, togishima commented on app/Http/Controllers/ReservationController.php
> +            'prevMonth' => $availabilityData->prevMonth->format('Y-m'),
ここのformat()ローカルでは削除したはずなんですがリモートには反映されてないんですよね…謎…

2021-03-27 12:42 UTC, Ryo-M-49 approved these changes
大変な機能の実装お疲れさまでした！

2021-03-27 12:42 UTC, merged